springboot-service:
  projectName: qacodemonitor
  cloudProvider: gke
  ingress:
    enabled: true
    hosts:
      - host: qacodemonitor-back.pre.srv.mercadona.com
        port: 80
        path: /web-main/api/v1
    tls: tls-crt-wildcard
  customSecret:
    enabled: true
    mountAsVolume: true
    readOnly: true
    # This name have to have the following nomenclature: <namespace-projectName-secrets>, replace it for your own project
    name: qacodemonitor-back-secrets
    mountPath: /var/run/secrets/
    # Replace your own GCP project id
    projectId: mdona-cloud-pre-qacodemonitor
    data:
      - remoteSecret: sonar-username # This corresponds to a Secret Manager's key in GCP console
        k8sKey: sonar-username
      - remoteSecret: sonar-password # This corresponds to a Secret Manager's key in GCP console
        k8sKey: sonar-password
      - remoteSecret: sonar_token # This corresponds to a Secret Manager's key in GCP console
        k8sKey: sonar_token
      - remoteSecret: adfs-pass-qacodemonitor # This corresponds to a Secret Manager's key in GCP console
        k8sKey: adfs-pass-qacodemonitor
      - remoteSecret: adfs-id-qacodemonitor # This corresponds to a Secret Manager's key in GCP console
        k8sKey: adfs-id-qacodemonitor
  extraEnv:
    - name: SPRING_PROFILES_ACTIVE
      value: pre
    - name: JAVA_MONITORING_OPTS_EXT
      value: -Dotel.otlp.span.timeout=4000 -Dotel.propagators=b3multi -Dotel.exporter.otlp.endpoint=http://opentelemetrycollector.opentelemetry.svc.cluster.local:4317 -Dotel.resource.attributes=service.name=qacodemonitor-back-web-main,deployment.environment=pre -Dotel.exporter.otlp.insecure=true -Dotel.exporter.otlp.traces.protocol=grpc -Dotel.traces.exporter=otlp -Dotel.javaagent.debug=false -Dotel.stryker.exporter=none
    - name: CONSOLE_LOG_PATTERN
      value: '{"level": "%level", "date": "%d{yyyy-MM-ddTHH:mm:ss.SSSZ}", "application": "%property{springAppName}", "pod": "%contextName", "thread": "%thread", "stacktrace": "%ex{full}" , "message": "%msg [%c{36}.%M \(%L\)]"}%n'
    - name: SONAR_USERNAME
      valueFrom:
        secretKeyRef:
          key: sonar-username
          name: qacodemonitor-back-secrets
    - name: SONAR_PASSWORD
      valueFrom:
        secretKeyRef:
          key: sonar-password
          name: qacodemonitor-back-secrets
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          key: sonar_token
          name: qacodemonitor-back-secrets
    - name: ADFS_ID_QACODEMONITOR
      valueFrom:
        secretKeyRef:
          key: adfs-id-qacodemonitor
          name: qacodemonitor-back-secrets
    - name: ADFS_SECRET_QACODEMONITOR
      valueFrom:
        secretKeyRef:
          key: adfs-pass-qacodemonitor
          name: qacodemonitor-back-secrets
  extraVolumes:
    - name: service-account-credentials
      secret:
        # The name is provided by infrastructure replace <secret-key-service-account> placeholder with the provided name
        secretName: sa-json-web-main
  overrideContainerPort: 8080
  service:
    internalPort: 8081
  envoy:
    enabled: true
    args:
      - -i
      - /config/swagger.yaml
      - -p
      - '"/web-main/api/v1:"'
      - '--corsAllowOrigin'
      - '"https?://.+\\.mercadona\\.(com|es)"'
      - '--corsAllowOrigin'
      - '"https?://localhost:4200"'
    env:
      - name: O2E_ISSUER_ADFS
        value: "http://fed.premercadona.com/adfs/services/trust"
      - name: O2E_JWKS_URI_ADFS
        value: "https://fed.premercadona.com/adfs/discovery/keys"
      - name: O2E_AUDIENCES_ADFS
        value: "api://mercadona/audience/services/qacodemonitor/v1"
    swaggerFiles:
      - api-rest/contracts/swagger.yaml
